### ISSUE TITLE
There is no "Exercise 1" folder

### ISSUE THREAD

**Issue by TomSoderling** [XamarinUniversity/AND102#1]
## What are you seeing?
"Open your copy of the cloned or downloaded Exercise 1 > Completed solution from your copy of the cloned or downloaded course materials in either Visual Studio for Windows or Visual Studio for Mac."

## What is expected?
There is no Exercise 1 folder in the download. So I'm guessing this text should be updated?

## What steps did you take to see this?
Went to step #4 in the self-guided learning. 
https://elearning.xamarin.com/android/and102/1-StartActivity/exercise1/0-open-solution

## Have any logged output/error messages that might help?
No, N/A

## About your system
Mac

### What operating system are you using? Windows? macOS?
Mac

### What version of Visual Studio are you using?
N/A

**Comment by adrianstevens** [comment]
Thx @TomSoderling you're absolutely right - the text should instruct you to open the completed solution in Exercise 6 folder. We'll get this fixed asap.

Thank you for taking the time to file an issue!

**Comment by adrianstevens** [comment]
fixed - closing

**Comment by TomSoderling** [comment]
Ah, that makes more sense. Thanks!
